ALTER TABLE usuarios
MODIFY COLUMN id INT AUTO_INCREMENT,
ADD PRIMARY KEY (id);

ALTER TABLE destinos
MODIFY COLUMN id INT AUTO_INCREMENT,
ADD PRIMARY KEY (id);

ALTER TABLE reservas
MODIFY COLUMN id INT AUTO_INCREMENT,
ADD PRIMARY KEY  (id);

ALTER TABLE reservas
ADD CONSTRAINT FK_RESERVAS_USUARIOS
FOREIGN KEY (id_usuario) REFERENCES usuarios (id)
ON DELETE CASCADE;

ALTER TABLE reservas
ADD CONSTRAINT FK_RESERVAS_DESTINOS
FOREIGN KEY (id_usuario) REFERENCES destinos (id);
