version: '3'

services:
  db:
    image: 'bitnami/mongodb:latest'
    ports:
      - 27017:271017
    restart: on-failure
    environment:
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ADVERTISED_HOSTNAME=localhost
      - ALLOW_EMPTY_PASSWORD=yes